### ISSUE TITLE
convert gps to lambert ?

### ISSUE THREAD

**Issue by smolleyes** [juliuste/projections#7]
hi

i can convert from classical gps lat/lng to lambert with your module (thanks)

but is it possible to convert to RGF93 - CC48 / NGF (IGN69)

?

thanks

**Comment by derhuerst** [comment]
@juliuste bump.

**Comment by juliuste** [comment]
(I forgot about this issue, sorry for that…)
Do you want to convert WGS84 -> RGF93 or something else -> RGF93?

**Comment by juliuste** [comment]
Is this question still open? Otherwise I'll close this issue.

**Comment by mycaule** [comment]
Hello, I tried to solve similar problem to the original poster.

Reading the docs of your library it it isn't clear how to convert Lambert 93 to WGS and backwards. Especially for people who aren't familiar with the different coordinate systems (like me).

There are code samples here
https://gist.github.com/liitfr/723abbfc6b8fefe01f5c918605b4d4e1

Here is a test case for a point located in Paris, France.
```
const p1 = { x: '653435', y: '6860703' } // Lambert 93
const p2 = toWGS(p1)
// { lat: 48.844689579677976, lon: 2.365510635426925 } // GPS
```
I would be interested to know how to do the same using projections library.

Thank you for your work by the way. 

I used to work for French railway company SNCF and it seems you have done lots of interesting stuff in your repos. I will have a look by curiosity!

The railway industry has plenty of interesting problems like this, which most IT people don't know about.

**Comment by juliuste** [comment]
Hello (:

For problems like this, I'd suggest that you use the `proj4` library instead, which can convert almost everything into everything.

The EPSG code for Lambert 93 is [`EPSG:2154`](http://spatialreference.org/ref/epsg/2154/), so you could do this:

```js
const proj4 = require('proj4')
const epsg = require('epsg')

// RGF93 (Lambert) to WGS84
let lambertCoordinates = {x: 653435, y: 6860703}
let wgsCoordinates = proj4(epsg['EPSG:2154'], 'WGS84', lambertCoordinates) // {x: longitude, y: latitude}

// WGS84 to RGF93 (Lambert)
wgsCoordinates = { x: 2.365510635424298, y: 48.844689579880104 } // x for longitude and y for latitude
lambertCoordinates = proj4('WGS84', epsg['EPSG:2154'], wgsCoordinates)
```

Does this help?

**Comment by derhuerst** [comment]
You can also use [`transform-coordinates`](https://github.com/derhuerst/transform-coordinates), which wraps around `proj4` to make it more user-friendly.

```js
const transformation = require('transform-coordinates')

const transform = transformation('EPSG:2154', 'WGS84')

console.error(transform.forward({x: 13.4105, y: 52.5034}))
```
